export const Palette = {
  ACCENT_COLOR: "#2ae2a4",
  BORDER_COLOR: "#bababa",
  BACKGROUND_COLOR: "#ffffff",
  LIST_ITEM_SELECTED_BORDER_COLOR: "#13654A",
  LIST_ITEM_SELECTED_BACKGROUND_COLOR: "#2AE2A4",
};
